# Generated by Django 3.2.25 on 2024-08-21 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('rent', 'Rent'), ('salary', 'Salary'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('dining', 'Dining'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('savings', 'Savings'), ('investments', 'Investments'), ('debt_payment', 'Debt Payment'), ('charity', 'Charity'), ('education', 'Education'), ('personal_care', 'Personal Care'), ('other', 'Other')], max_length=50)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
