# Generated by Django 5.0.3 on 2024-09-11 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0004_remove_plaidaccount_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccount',
            name='account_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
