# Generated by Django 5.0.3 on 2024-10-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0005_plaidaccount_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidaccount',
            name='account_id',
        ),
    ]
