# Generated by Django 5.0.3 on 2024-10-05 18:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0006_remove_plaidaccount_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('plaid_account_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_manager.account')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_manager.goal')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='accounts',
            field=models.ManyToManyField(related_name='goals', through='finance_manager.GoalAccount', to='finance_manager.account'),
        ),
        migrations.DeleteModel(
            name='AccountSummary',
        ),
    ]
