# Generated by Django 5.0.3 on 2024-10-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0007_account_goalaccount_goal_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalaccount',
            name='contribution_amount',
        ),
    ]
