# Generated by Django 5.0.3 on 2024-10-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0008_remove_goalaccount_contribution_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalAssociatedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_manager.account')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_manager.goal')),
            ],
        ),
    ]
